
build:
	docker build \
    		   --build-arg database=greetings \
    		   --build-arg root_password=root \
    		   --build-arg changelog_dir=changelog \
    		   --build-arg changelog_master=changelog-master.json \
    		   -t  greetings .